variables:
  Agent.Source.Git.ShallowFetchDepth: 1

trigger:
- master

jobs:
- job: Build
  pool:
    vmImage: 'macOS-10.14'
    maxParallel: 4

  steps:
  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      sudo chown -R $USER $CONDA
    displayName: Add conda to PATH
  - bash: |
      conda env create -f environment_macOS.yml
    displayName: Create Conda environment
  - bash: |
      source activate simnibs_env
      python setup.py bdist_wheel
      cp dist/* $(Build.ArtifactStagingDirectory)
      cp environment_macOS.yml $(Build.ArtifactStagingDirectory)
    displayName: Build SimNIBS
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: osx_wheel
    displayName: Publish Artifact

- job: Test
  dependsOn: Build
  strategy:
    matrix:
      MacOSX-10.14:
        vmImage: 'macOS-10.14'

  pool:
    vmImage: $(vmImage)
    maxParallel: 4

  steps:
  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      sudo chown -R $USER $CONDA
    displayName: Add conda to PATH
  - bash: |
      sed '/pyopengl/d;/freeglut/d;/qt/d' environment_macOS.yml  > env.yml
      conda env create -f env.yml
    displayName: Create conda environment
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'osx_wheel'
      downloadPath: '$(System.ArtifactsDirectory)'
    displayName: Download Wheel

  - bash: |
      source activate simnibs_env
      pip install -f file://$(System.ArtifactsDirectory)/osx_wheel simnibs
      pytest simnibs/tests --junit-xml=test-results.xml
    displayName: Install SimNIBS and run unit tests
  
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: 'test-results.xml'
      testRunTitle: 'Publish test results'
      
# If everything went fine, we upload the wheel as a draft to GitHub
- job: Release
  dependsOn: Test
  pool:
    vmImage: 'ubuntu-16.04'

  steps:

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'osx_wheel'
      downloadPath: '$(System.ArtifactsDirectory)'
    displayName: Download Wheel

  - task: GithubRelease@0
    displayName: Edit GitHub Release
    inputs: 
      gitHubConnection: guilhermebs # I use my connection because github does not generate OAuth token for organizations
      repositoryName: simnibs/simnibs
      action: edit
      tag: dev
      assets: $(System.ArtifactsDirectory)/osx_wheel/*
      assetUploadMode: 'replace'
      isDraft: true
